# Linear Algebra

In [1]:
import numpy as np

In [5]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

#### 1. Addition and Subtraction

In [4]:
print("Addition :\n ",A+B)
print("\n Subtration :\n ",A-B)

Addition :
  [[ 6  8]
 [10 12]]

 Subtration :
  [[-4 -4]
 [-4 -4]]


#### 2. Scalar Multiplication

In [7]:
C = 2*A
print("Scalar Multiplication: \n ",C)

Scalar Multiplication: 
  [[2 4]
 [6 8]]


#### 3. Matrix Multiplication

In [8]:
result = np.dot(A,B)
print("Matrix Multiplication :\n ",result)

Matrix Multiplication :
  [[19 22]
 [43 50]]


#### 4. Special matrix

##### a. Identity matrix

In [9]:
I = np.eye(3)
print("Identity matrix: \n ", I)

Identity matrix: 
  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### b. Zero matrix

In [10]:
Z = np.zeros((3,3))
print("Zero matrix: \n" , Z)

Zero matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##### c. Diagonal matrix

In [11]:
D = np.diag([1,2,3])
print("Diagonal matrix: \n", D)

Diagonal matrix: 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


#### 5. Matrix - Vector multiplication

In [13]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
V = np.array([1,0,-1])
print("Matrix - Vector multiplication : \n ",np.dot(M,V))

Matrix - Vector multiplication : 
  [-2 -2 -2]


#### 6. Explore special matrix

In [14]:
I = np.eye(3)
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A X I : \n ",np.dot(I,A))

A X I : 
  [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [16]:
D = np.diag([1,2,3])
Z = np.zeros((3,3))
print("Diagonal matrix: \n", D)
print("\n Zero matrix: \n" , Z)
print("\n D X Z : \n ",np.dot(D,Z))

Diagonal matrix: 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]

 Zero matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 D X Z : 
  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### 7. Determinant of 2X2 matrix

In [3]:
import numpy as np
A = np.array([[1,2],[3,4]])
determinant = np.linalg.det(A)
print("Determinant of A :\n ", determinant)

Determinant of A :
  -2.0000000000000004


#### 8. inverse of 2X2 matrix

In [4]:
inverse = np.linalg.inv(A)
print("Inverse of A :\n ", inverse)

Inverse of A :
  [[-2.   1. ]
 [ 1.5 -0.5]]


#### 9. Eigen values and Eigen vectors

In [6]:
eigenVal,eigenVec = np.linalg.eig(A)
print("Eigen values of A :\n ",eigenVal )
print("Eigen vectors of A :\n ",eigenVec )

Eigen values of A :
  [-0.37228132  5.37228132]
Eigen vectors of A :
  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


#### 10. Matrix decomposition : SVD

In [8]:
U,S,Vt = np.linalg.svd(A)
print("U :\n ", U)
print("S :\n ", S)
print("Vt  :\n ", Vt)

U :
  [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S :
  [5.4649857  0.36596619]
Vt  :
  [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [14]:
# reconstruct
sigma = np.zeros((2,2))
np.fill_diagonal(sigma,S)
reconstructed = U @ sigma @ Vt
print("Reconstructed matrix :\n ", reconstructed)

Reconstructed matrix :
  [[1. 2.]
 [3. 4.]]
